"""Simplify tender model to 5 fields only

Revision ID: 9c0fce5de3bf
Revises: 22c97c0eb2f7
Create Date: 2026-06-30 17:40:24.938804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c0fce5de3bf'
down_revision = '22c97c0eb2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('scraped_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('deadline',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_tenders_source_reference'))
        batch_op.create_index(batch_op.f('ix_tenders_reference'), ['reference'], unique=True)
        batch_op.drop_column('description')
        batch_op.drop_column('estimated_value')
        batch_op.drop_column('status')
        batch_op.drop_column('source_urls')
        batch_op.drop_column('matched_topics')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('relevance_score')
        batch_op.drop_column('created_at')
        batch_op.drop_column('category')
        batch_op.drop_column('match_explanation')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('source_reference')
        batch_op.drop_column('language')
        batch_op.drop_column('region')
        batch_op.drop_column('first_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('source_reference', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_explanation', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('matched_topics', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('source_urls', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estimated_value', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_tenders_reference'))
        batch_op.create_index(batch_op.f('ix_tenders_source_reference'), ['source_reference'], unique=True)
        batch_op.alter_column('deadline',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('scraped_at')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
