"""Add scraper_configs table

Revision ID: f6f3619afb26
Revises: 9c0fce5de3bf
Create Date: 2026-08-06 18:59:05.933370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6f3619afb26'
down_revision = '9c0fce5de3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('auth_type', sa.String(length=20), nullable=True),
    sa.Column('auth_config', sa.Text(), nullable=True),
    sa.Column('parser_config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_scraped', sa.DateTime(), nullable=True),
    sa.Column('total_tenders', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('partition_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partition_memberships_partition_name'))
        batch_op.drop_index(batch_op.f('ix_partition_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_partition'))

    op.drop_table('partition_memberships')
    with op.batch_alter_table('workspace_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_files_file_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_files_workspace_id'))

    op.drop_table('workspace_files')
    with op.batch_alter_table('partitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partitions_created_at'))
        batch_op.drop_index(batch_op.f('ix_partitions_partition'))

    op.drop_table('partitions')
    op.drop_table('pipeline_presets')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_created_by'))
        batch_op.drop_index(batch_op.f('ix_files_file_id'))
        batch_op.drop_index(batch_op.f('ix_files_parent_id'))
        batch_op.drop_index(batch_op.f('ix_files_partition_name'))
        batch_op.drop_index(batch_op.f('ix_files_relationship_id'))
        batch_op.drop_index(batch_op.f('ix_parent_partition'))
        batch_op.drop_index(batch_op.f('ix_partition_file'))
        batch_op.drop_index(batch_op.f('ix_relationship_partition'))

    op.drop_table('files')
    op.drop_table('chunks')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_partition_name'))
        batch_op.drop_index(batch_op.f('ix_workspaces_workspace_id'))

    op.drop_table('workspaces')
    op.drop_table('model_endpoints')
    with op.batch_alter_table('oidc_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oidc_sessions_session_token_hash'))
        batch_op.drop_index(batch_op.f('ix_oidc_sessions_sid'))
        batch_op.drop_index(batch_op.f('ix_oidc_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_oidc_sessions_user_sub'))

    op.drop_table('oidc_sessions')
    with op.batch_alter_table('topic_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_tags_document_id'))
        batch_op.drop_index(batch_op.f('ix_topic_tags_partition'))
        batch_op.drop_index(batch_op.f('ix_topic_tags_partition_tag'))

    op.drop_table('topic_tags')
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('source_url')
        batch_op.drop_column('description')
        batch_op.drop_column('indexed_at')
        batch_op.drop_column('content')
        batch_op.drop_column('file_path')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_column('file_quota')
        batch_op.drop_column('display_name')
        batch_op.drop_column('is_superuser')
        batch_op.drop_column('full_name')
        batch_op.drop_column('token')
        batch_op.drop_column('file_count')
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('external_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_quota', sa.INTEGER(), server_default=sa.text("'-1'::integer"), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('indexed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    op.create_table('topic_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('normalized_tag', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id', 'partition'], ['files.file_id', 'files.partition_name'], name=op.f('fk_topic_tags_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_tags_pkey')),
    sa.UniqueConstraint('document_id', 'partition', 'normalized_tag', name=op.f('uix_topic_tags_document_partition_tag'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('topic_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_tags_partition_tag'), ['partition', 'normalized_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_tags_partition'), ['partition'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_tags_document_id'), ['document_id'], unique=False)

    op.create_table('oidc_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sub', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_token_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('access_token_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('refresh_token_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('access_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('session_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_refresh_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('oidc_sessions_pkey'))
    )
    with op.batch_alter_table('oidc_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oidc_sessions_user_sub'), ['user_id', 'sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_oidc_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oidc_sessions_sid'), ['sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_oidc_sessions_session_token_hash'), ['session_token_hash'], unique=True)

    op.create_table('model_endpoints',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('batch_size', sa.INTEGER(), server_default=sa.text('32'), autoincrement=False, nullable=False),
    sa.Column('timeout', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'30'::double precision"), autoincrement=False, nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("model_type::text = ANY (ARRAY['embedder'::character varying, 'reranker'::character varying, 'llm'::character varying, 'vlm'::character varying]::text[])", name=op.f('ck_model_endpoint_type')),
    sa.PrimaryKeyConstraint('name', 'model_type', name=op.f('model_endpoints_pkey'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partition_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partition_name'], ['partitions.partition'], name=op.f('workspaces_partition_name_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspaces_pkey'))
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_workspace_id'), ['workspace_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workspaces_partition_name'), ['partition_name'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('chunk_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chunks_pkey'))
    )
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partition_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relationship_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('indexation_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('indexed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partition_name'], ['partitions.partition'], name=op.f('files_partition_name_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey')),
    sa.UniqueConstraint('file_id', 'partition_name', name=op.f('uix_file_id_partition'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_partition'), ['relationship_id', 'partition_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_partition_file'), ['partition_name', 'file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_partition'), ['parent_id', 'partition_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_relationship_id'), ['relationship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_partition_name'), ['partition_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_created_by'), ['created_by'], unique=False)

    op.create_table('pipeline_presets',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preset_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("preset_type::text = ANY (ARRAY['indexation'::character varying, 'retrieval'::character varying]::text[])", name=op.f('ck_pipeline_preset_type')),
    sa.PrimaryKeyConstraint('name', 'preset_type', name=op.f('pipeline_presets_pkey'))
    )
    op.create_table('partitions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('embedder', sa.VARCHAR(), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.Column('indexation_preset', sa.VARCHAR(), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.Column('retrieval_preset', sa.VARCHAR(), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.INTEGER(), server_default=sa.text('1024'), autoincrement=False, nullable=False),
    sa.Column('collection_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chat_history_depth', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('chat_llm', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('partitions_pkey'))
    )
    with op.batch_alter_table('partitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partitions_partition'), ['partition'], unique=True)
        batch_op.create_index(batch_op.f('ix_partitions_created_at'), ['created_at'], unique=False)

    op.create_table('workspace_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_workspace_files_file_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('workspace_files_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_files_pkey')),
    sa.UniqueConstraint('workspace_id', 'file_id', name=op.f('uix_workspace_file'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('workspace_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_files_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_files_file_id'), ['file_id'], unique=False)

    op.create_table('partition_memberships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partition_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['owner'::character varying, 'editor'::character varying, 'viewer'::character varying]::text[])", name=op.f('ck_membership_role')),
    sa.ForeignKeyConstraint(['partition_name'], ['partitions.partition'], name=op.f('partition_memberships_partition_name_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('partition_memberships_pkey')),
    sa.UniqueConstraint('partition_name', 'user_id', name=op.f('uix_partition_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('partition_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_partition'), ['user_id', 'partition_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_partition_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partition_memberships_partition_name'), ['partition_name'], unique=False)

    op.drop_table('scraper_configs')
    # ### end Alembic commands ###
